### ISSUE TITLE
HTTPS protocol support for greentea GRM

### ISSUE THREAD

**Issue by RomanSaveljev** [ARMmbed/mbed-os-tools#103]
To support the changes in our infrastructure we need greentea to support connecting with GRM over HTTPS. Looks like the necessary change is small and belongs [here](
https://github.com/ARMmbed/mbed-os-tools/blob/b73bad309e76cf5e730ed53415999de778853738/src/mbed_os_tools/test/host_tests_runner/host_test_default.py#L195).

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
