### ISSUE TITLE
[DISCO_L475VG_IOT01A]Privacy: App compilation fails with fatal error

### ISSUE THREAD

**Issue by UrmilaKL** [ARMmbed/mbed-os-tools#112]
Description: [DISCO_L475VG_IOT01A]Privacy: App compilation fails with fatal error

Target: DISCO_L475VG_IOT01A
Toolchain: GCC_ARM
mbed-cli version: 1.8.3
mbed-os->5.11.1
App used: mbed-os-example-ble-privacy

Steps to Reproduce:
1. .Import project from https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-ble-privacy/
2. Edit the mbed-os.lib file to below link to 
https://github.com/ARMmbed/mbed-os/#2fd0c5cfbd83fce62da6308f9d64c0ab64e1f0d6
3. Do mbed deploy to update mbed-os to use the above revision
4. Do mbed compile -target DISCO_L475VG_IOT01A -toolchain GCC_ARM

Expectation: App compilation and download should be successful 

Observation: Privacy app compilation fails with below error
"[ERROR] .\source\main.cpp:19:21: fatal error: ble/BLE.h: No such file or directory"

Please find the attached logs for compilation error
[PrivacyFailureOnDisco.txt](https://github.com/ARMmbed/mbed-os-tools/files/2786987/PrivacyFailureOnDisco.txt)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-788*

**Comment by bridadan** [comment]
Hi @UrmilaKL, it's possible that that repository is out of date.

To confirm can you try the equivalent repository from github? Please follow the instructions here: https://github.com/ARMmbed/mbed-os-example-ble#building-and-testing-the-examples

And replace `cd BLE_Beacon` with `cd BLE_Privacy`.

**Comment by bridadan** [comment]
Hi @UrmilaKL, any update?

**Comment by UrmilaKL** [comment]
Hi @bridadan,

Now compilation and download is working fine with DISCO board, If possible could you please add the changes to the below link also as we are taking the examples from this link only

**Comment by bridadan** [comment]
> If possible could you please add the changes to the below link also as we are taking the examples from this link only

I don't quite follow, could you clarify what link you're talking about and which examples? (Github vs Mbed site, etc)

**Comment by UrmilaKL** [comment]
HI @bridadan ,

We are picking all the mbed OS BLE examples from the below link could you please update it here?
https://os.mbed.com/search/repository?q=mbed-os-examples-BLE

Thanks and Regards
Urmila Bhat

**Comment by bridadan** [comment]
I see, thanks for clarifying. I'm working to get that example copy updated.

**Comment by ConradBraam** [comment]
@bridadan Just pushed an example update, and am improving on issues in this repo too, do link up.

**Comment by bridadan** [comment]
Thanks @ConradBraam.

@UrmilaKL this example has now been updated: https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-ble-Privacy/

Thanks for your patience.
