### ISSUE TITLE
mbedls: extend mock option to a specific target_id

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-tools#125]
### Description

Hi

Idea is to be able to configure in my local system some specific HW boards.

Ex:
- 1 board with a Arduino shield
- 1 board configured with a non default setting

I could use the mock command :

$ mbedls

| platform_name       | platform_name_unique   | mount_point | serial_port | target_id                | daplink_version |
|---------------------|------------------------|-------------|-------------|--------------------------|-----------------|
| DISCO_L475VG_IOT01A | DISCO_L475VG_IOT01A[0] | E:          | COM30       | 076402216E2E6517516AF34E | 0221            |

$ mbedls -m 0764:DISCO_V1

$ mbedls

WARNING:mbedls.platform_database:Duplicate platform ids found: daplink.0764, ignoring the definitions from 

| platform_name | platform_name_unique | mount_point | serial_port | target_id                | daplink_version |
|---------------|----------------------|-------------|-------------|--------------------------|-----------------|
| DISCO_V1      | DISCO_V1[0]          | E:          | COM30       | 076402216E2E6517516AF34E | 0221            |

My “ideal” command would be:

$ mbedls -m 076402216E2E6517516AF34E:DISCO_V1

Which change the name of only 1 board, other DISCO_L475VG_IOT01A will keep the original name

Do you think it could be possible ?

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-830*

**Comment by jeromecoutant** [comment]
This would be currently very useful for us for cortex M33 integration.
We configured some boards with security, and some boards keep the default non secure values.
Thx

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
