### ISSUE TITLE
mbed deploy fails with Python 3.7 on Windows 10 if project directory contains binary .lib files

### ISSUE THREAD

**Issue by desowin** [ARMmbed/mbed-os-tools#134]
### Description

Within the project directory I have msvc library files whose extension is .lib. This file is not itself related to mbed in any way, and the whole directory containing the .lib files is included in `.mbedignore` file.

`mbed deploy` does not ignore the .lib files that are in `.mbedignore`. Thus it tries to load the binary file using local encoding, which fails on Windows if using Python 3.7. If Python 2.7 is used, then mbed works and prints the "non-standard .lib file extension" warning.

Example commands to reproduce the issue (in Mingw shell):
* `mbed new invalid-lib-example`
* `cd invalid-lib-example`
* `mkdir binary-lib`
* `echo -n -e \\x81\\x82\\x83\\x84 > binary-lib/dummy.lib`
* `echo "binary-lib/*" >> .mbedignore`
* `mbed deploy`

The `mbed deploy` command fails. The verbose output is:
```
$ mbed deploy -vv
[mbed] WARNING: If you're using Python 3 with Mbed OS 5.8 and earlier versions, Python errors will occur when compiling, testing and exporting
---
[mbed-10120] Working path "c:\work\mbed\invalid-lib-example" (program)
[mbed-10120] Exec "git remote -v" in "c:\work\mbed\invalid-lib-example"

[mbed-10120] Exec "git rev-parse HEAD" in "c:\work\mbed\invalid-lib-example"
HEAD
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 3389, in main
    status = pargs.command(pargs)
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 2020, in thunk
    return command(**argv)
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 2269, in deploy
    repo = Repo.fromrepo()
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 1079, in fromrepo
    repo.sync()
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 1189, in sync
    self.libs = list(self.getlibs())
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 1295, in getlibs
    repo = Repo.fromlib(os.path.join(root, f))
  File "c:\python37\lib\site-packages\mbed\mbed.py", line 1050, in fromlib
    ref = f.read(200)
  File "c:\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 0: character maps to <undefined>
[mbed-10120] ERROR: Unknown Error: 'charmap' codec can't decode byte 0x81 in position 0: character maps to <undefined>
---
[mbed-10120] WARNING: Using Python 3 with Mbed OS 5.8 and earlier can cause errors with compiling, testing and exporting
---
```

The expected behaviour is to either make `mbed deploy` ignore the files from `.mbedignore` or to work the same as when run with Python 2.7. The output when running with Python 2.7 is:
```
C:\work\mbed\invalid-lib-example>c:\Python27\Scripts\mbed.exe deploy
[mbed] Working path "C:\work\mbed\invalid-lib-example" (program)
[mbed] WARNING: File "dummy.lib" in "C:\work\mbed\invalid-lib-example\binary-lib" uses a non-standard .lib file extension, which is not compatible with the mbed build tools.
---
[mbed] Updating library "mbed-os" to rev #51d55508e840 (tags: latest, mbed-os-5.11.5)
```

### Issue request type

    [ ] Question
    [ ] Enhancement
    [X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-938*

**Comment by bridadan** [comment]
Hi @desowin, as you rightly realized in https://github.com/ARMmbed/mbed-cli/issues/859#issuecomment-468563932, this is a duplicate issue. I will close this issue since the fix will need to land in Mbed CLI. Thanks for the detailed report!

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
