### ISSUE TITLE
mbed-cli, Mercurial, Python 2 defaults

### ISSUE THREAD

**Issue by dlfryar** [ARMmbed/mbed-os-tools#135]
### Description

Latest tools installed on an OS that only has Python3 will error when using mbed-cli if Mercurial/Python2 are not installed.

Py2 is going EOL January 2020:
https://pythonclock.org
https://legacy.python.org/dev/peps/pep-0373/

Mercurial is currently based on Py2 and Py3 refactor is in beta:
https://www.mercurial-scm.org/wiki/Python3

```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

```
python -V
Python 3.7.2
```

```
pip -V
pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

```
pip freeze | grep mbed
mbed-cli==1.9.1
mbed-cloud-sdk==2.0.5
mbed-flasher==0.10.1
mbed-greentea==1.6.2
mbed-host-tests==1.5.2
mbed-ls==1.7.2
mbed-os-tools==0.0.3
```

mbed import https://github.com/armmbed/mbed-os-example-blinky

```
[mbed] ERROR: Could not execute "hg clone ...
```

git clone https://github.com/armmbed/mbed-os-example-blinky && cd mbed-os-example-blinky
mbed deploy

```
[mbed] ERROR: Could not execute "hg clone ...
```

### workaround without Mercurial/Py2

git clone https://github.com/armmbed/mbed-os
cd mbed-os && mbed update && cd ..
mbed compile
### Issue request type

    [ ] Question
    [X] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-959*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
