### ISSUE TITLE
parse_global_resource_mgr(...) default port = None -> ':'.join(grm_values[1:]) -> TypeError

### ISSUE THREAD

**Issue by alekla01** [ARMmbed/mbed-os-tools#141]
### Description

port_name = None, https://github.com/ARMmbed/mbed-os-tools/blob/master/src/mbed_os_tools/test/mbed_test_api.py#L582
':'.join(grm_values[1:]), https://github.com/ARMmbed/mbed-os-tools/blob/master/packages/mbed-greentea/mbed_greentea/mbed_greentea_cli.py#L697
-> TypeError: sequence item 2: expected string, NoneType found

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1027*

**Comment by bridadan** [comment]
Hi @alekla01, could you please provide the command you ran to get this error?

**Comment by alekla01** [comment]
@bridadan 
````
--grm target:client:url -> TypeError
--grm target:client:url:port -> no error
````

**Comment by bridadan** [comment]
Hi @alekla01,

I have a test case specifically for this case:

- Using raw IP address: https://github.com/ARMmbed/mbed-os-tools/commit/36610815fd4425ed3162057411f8b578216c5faf#diff-5f374df9fc07e86f5e318ab930107fb1R607
- Using a URL with a protocol: https://github.com/ARMmbed/mbed-os-tools/commit/36610815fd4425ed3162057411f8b578216c5faf#diff-5f374df9fc07e86f5e318ab930107fb1R615

Could you please provide the following so I can accurately reproduce the error:

- The output of `pip list` (looking for the versions of various python packages on your system
- The full command that you are executing. (specifically interested in the **unmodified** `--grm` argument. If you can't share it publicly you can always email me internally, thanks)
