### ISSUE TITLE
ST-LINK Plugin bug.

### ISSUE THREAD

**Issue by embeddedteam103** [ARMmbed/mbed-os-tools#147]
### Description
Duplicate of https://github.com/ARMmbed/htrun/issues/205
We have also ran into the same issue.

### Issue request type

    [ ] Question
    [ ] Enhancement
    [x] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1058*
