### ISSUE TITLE
Bumping up DAPLink interfaces will/may happen in the near future

### ISSUE THREAD

**Issue by brianesquilona** [ARMmbed/mbed-os-tools#152]
### Issue request type

    [ ] Question
    [x] Enhancement
    [x] Bug

[https://github.com/ARMmbed/mbed-os-tools/blob/master/src/mbed_os_tools/detect/windows.py#L36](https://github.com/ARMmbed/mbed-os-tools/blob/master/src/mbed_os_tools/detect/windows.py#L36) needs future proofing.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1074*

**Comment by loverdeg-ep** [comment]
@brianesquilona What is the issue?

**Comment by bridadan** [comment]
@loverdeg-ep we looked at this offline, but basically @brianesquilona was experimenting with the composite USB device of the firmware and found that Mbed LS would no longer detect the mount point for the device. I'm pretty sure this is the reason for his particular issue (I asked him to put up an issue so we didn't lose track of it).

**Comment by loverdeg-ep** [comment]
My comment should have been more descriptive.
I'm a fan of most things DAPLink and was just curious what "bumping up" meant.

I checked the linked line of code and assumed increasing the number of devices within the composite but was lost as to the context of the issue.

**Comment by bridadan** [comment]
@brianesquilona told me offline that this change will no longer be needed, so closing this now.
