### ISSUE TITLE
What is "stable" vs not?

### ISSUE THREAD

**Issue by Alex-EEE** [ARMmbed/mbed-os-tools#163]
### Description

Hi,

We're trying to migrate from the old htrun repo to this one.  Where should we add ( locally ) our jlink plugin?  Does it go under src/mbed-os-tools/test/host_test_plugins ?  There's also htrun under packages.  What files are "stable" are what aren't exactly?  

### Issue request type

    [x] Question
    [ ] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1178*

**Comment by bridadan** [comment]
Hi @Alex-EEE, thanks for the question. Please add the plugin to `src/mbed-os-tools/test/host_tests_plugins`.

As to what is stable, basically the command line interface for mbedgt, mbedhtrun, and mbedls are stable. The module functions and organization inside of the `mbed-os-tools` package is not stable (we reserve the right to refactor/clean up all the code in that package). The idea being if we change the API in `mbed-os-tools`, we'll make sure we don't break the functionality at the command line level in mbedgt, mbedhtrun, and mbedls.
