### ISSUE TITLE
Need to change encoding in conn_primitive_serial.py file

### ISSUE THREAD

**Issue by viva-cy** [ARMmbed/mbed-os-tools#181]
Several test suites (e.g. MbedTLS test-suite) use this file to send test vectors which are "binary" data (contains characters from 0x00 to 0xff).
The Python 3.x has stronger rules to encoding data then Python 2.x and arrays which were encoded by Python 3.x and Python 2.x are different.
So, I provide to change Line #119:
    from    self.serial.write(payload.encode('utf-8'))
    to      self.serial.write(payload.encode('raw_unicode_escape'))

that will allow sending any data through serial interface.

---
mbed-os-tools: 0.0.8
Python 3.7
File: src/mbed_os_tools/test/host_tests_conn_proxy/conn_primitive_serial.py
Line #119
    was       self.serial.write(payload.encode('utf-8'))
    to be     self.serial.write(payload.encode('raw_unicode_escape'))

### Issue request type
    [ ] Question
    [ ] Enhancement
    [X] Bug

Thanks.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1234*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
This was closed by the automated bot by mistake - re-opening
