### ISSUE TITLE
Use the same mbed target Id for different mbed-os target

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-tools#182]
### Description

I would like to have different HW package using the same mbed target Id.

In mbedls, database is configuring each target:
- u"1234": u"MY_TARGET",

In targets.json mbed-os file, the detect_code macro can be available and is no more used.

    "MY_TARGET": {
        "detect_code": ["1234"],

Proposition is to re-use it, and to be able to create a new target using the same detect code Id.

    "MY_NEW_TARGET": {
        "detect_code": ["1234"],

mbed test command could work for both targets:

mbed test -m MY_TARGET
	will work as usual

mbed test -m MY_NEW_TARGET
	will work, even if MY_NEW_TARGET is not in mbedls database

Maybe it could be easier to use directly the target name to detect:

    "MY_NEW_TARGET": {
        "detect_code": ["MY_TARGET"],

@MarceloSalazar 
@LMESTM 

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by MarceloSalazar** [comment]
@jeromecoutant thanks for raising this request. I agree with you and believe it's important to have this place to let us introduce different variances of platforms that may require a slightly different configuration.

FYI @ARMmbed/mbed-os-maintainers

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1285*

**Comment by jeromecoutant** [comment]
Any chance to get this update soon,
or it is better to find a workaround ? :-)

**Comment by mark-edgeworth** [comment]
Hi @jeromecoutant, I'm sorry but it is unlikely we'll get to this anytime soon.

**Comment by mark-edgeworth** [comment]
Just for the record: the target names are currently restricted to a maximum of 20 characters...

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
