### ISSUE TITLE
Timestamps printed by mbedhtrun are not easily readable

### ISSUE THREAD

**Issue by matthew-macovsky-cypress** [ARMmbed/mbed-os-tools#195]
### Description

Currently, `mbedhtrun` prints the time with each log message as the number of milliseconds since the epoch, which is not very human-readable.  [Since this appears to be set up via python's logging module](https://github.com/ARMmbed/mbed-os-tools/blob/master/src/mbed_os_tools/test/host_tests_logger/ht_logger.py#L25), I would suggest changing the line

`logging.basicConfig(stream=sys.stdout,format='[%(created).2f][%(name)s]%(message)s', level=logging.DEBUG)`

to either

`logging.basicConfig(stream=sys.stdout,format='[%(relativeCreated)d][%(name)s]%(message)s', level=logging.DEBUG)`

to print the number of milliseconds since the module was imported, or something like

`logging.basicConfig(stream=sys.stdout,format='[%(asctime)s][%(name)s]%(message)s',datefmt="%H:%M:%S",level=logging.DEBUG)`

to print the date/time in a custom format.

### Issue request type

    [ ] Question
    [x] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-372*

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
