### ISSUE TITLE
MbedStudio / target mocking

### ISSUE THREAD

**Issue by pfried** [ARMmbed/mbed-os-tools#201]
### Description

The mbedls library provides a way to add custom targets by overriding an existing target (mock). This works also by putting a `mbedls.json` file in the `CWD` of the library.

As I guess MbedStudio also uses the library to do the auto target detection I wondered if it was possible to fake a custom target to MbedStudio? If the above mechanism works, where to put the file?

### Issue request type

    [x] Question
    [ ] Enhancement
    [ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTBTOOL-441*

**Comment by madchutney** [comment]
Hi Friedrich,

Can you please ask questions on our forum site, where the appropriate team will be able to answer your question:
- https://forums.mbed.com/c/More-on-our-next-gen-desktop-IDE

Thanks,
Graham

**Comment by pfried** [comment]
Hi Graham,

I did, so for reference: https://forums.mbed.com/t/custom-targets-debugging-and-auto-detection/6177

Best, Friedrich

**Comment by madchutney** [comment]
👍 Thanks
