### ISSUE TITLE
Greentea to test main application

### ISSUE THREAD

**Issue by Nakul93** [ARMmbed/mbed-os-tools#238]
### Issue request type

    [x] Question
    [ ] Enhancement
    [ ] Bug

Can we use greentea to directly test a function inside a main.cpp file rather than testing the test cases in test suite?

**Comment by 40Grit** [comment]
This belongs in the forum but the answer is yes as long as you have your tests in a main.cpp in a folder named 'TEST'. 

Probably a way to use symlinks to accomplish this if you actually want your tests built into your application for whatever reason.

**Comment by Nakul93** [comment]
How exactly do I use symlinks here could you explain.
