### ISSUE TITLE
[detect] Add support for public endpoint with boards, procuct codes etc.

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/mbed-os-tools#67]
There is now a public https://www.mbed.com/api/v1/boards/ endpoint. It exposes all public boards. It contains information about product code, features, targets (classic, mbed os 5, yotta) and more. There is also similar endpoint on developer.mbed.org site but it requires token to get this information.

See `IOTWEB-1105` for more details.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
