### ISSUE TITLE
[test] Be more robust in log parsing

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-tools#68]
Consider the following example logs.

### Good log

```
** Hello Example **
Main loop count: 0
Main loop count: 1
Main loop count: 2
Main loop count: 3
Main loop count: 4
Main loop count: 5
Main loop count: 6
Main loop count: 7
Main loop count: 8
Main loop count: 9
Main loop count: 10
IRQ 1 from Button 1 Pressed
Main loop count: 11
Main loop count: 12
Main loop count: 13
Main loop count: 14
Main loop count: 15
```

### Bad log
```
** Hello Example **
Main loop count: 0
Main loop count: 1
Main loop count: 2
Main loop count: 3
Main loop count: 4
Main loop count: 5
** Out of memory
Main loop count: 6
Main loop count: 7
Main loop count: 8
Main loop count: 9
Main loop count: 10
IRQ 1 from Button 1 Pressed
Main loop count: 11
Main loop count: 12
Main loop count: 13
Main loop count: 14
Main loop count: 15
```

### Good log
```
** Hello Example **
Main loop count: 0
Main loop count: 1
Main loop count: 2
Main loop count: 3
Main loop count: 4
Main loop count: 5
Main loop count: 6
Main loop count: 7
Main loop count: 8
Main loop count: 9
Main loop count: 10
Main loop count: 11
IRQ 1 from Button 1 Pressed
Main loop count: 12
Main loop count: 13
Main loop count: 14
Main loop count: 15
```

These logs are impossible to match with the current log matching functionality. The current log matching feature (for both programmer implementation and user cognitive overhead) would be simplified by matching with a single multi-line regular expression.

### Example log matcher
The following multi-line regular expression would deal with the asynchronicity of the previous logs, where the IRQ could come at basically any time relative to the "Main loop count" lines. It would also fail to match if the `** Out of memory` print happened at any time from some other thread in the system.

```
(\*\* Hello Example \*\*\r\n)(Main loop count: \d+\r\n)+(IRQ \d+ from Button \d+ Pressed\r\n)(Main loop count: \d+\r\n)
```

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
