### ISSUE TITLE
[test] Add user reset

### ISSUE THREAD

**Issue by geky** [ARMmbed/mbed-os-tools#69]
I noticed there's a plugin system in place for adding additional reset logic.

It would be awfully convenient to have a reset option that simply queries the user to reset the device, and waits for the user to push a key or something.

I'm currently dealing with a board that must be power cycled for the necessary hardware blocks to initialize correctly (it's a long story). Having a user-based reset would be very convenient.

cc @studavekar, @theotherjimmy

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
