### ISSUE TITLE
[test] All of the host test modules start with `host_tests`

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/mbed-os-tools#70]
This is very very redundant. I'm not sure if anyone even imports them.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
