### ISSUE TITLE
[test] Figure out consumers of the "toolbox" api

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-os-tools#71]
The apis contained within https://github.com/ARMmbed/htrun/tree/master/mbed_host_tests/host_tests_toolbox do not seemed to be used within `htrun` (with the exception of `handle_send_break_cmd`, which can be relocated).

It is being used by Mbed CLI: https://github.com/ARMmbed/mbed-cli/blob/master/mbed/mbed.py#L2689

It would be good to know if any other tools are using this API so we can maintain it as a public API. Currently what we define as "public" is a bit ambiguous.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
