### ISSUE TITLE
[test] feature request: st-flash copy/reset module

### ISSUE THREAD

**Issue by talorion** [ARMmbed/mbed-os-tools#73]
Hey guys,
i am working on linux and i was wondering if you could include a copy/reset module for this:
[st-flash](https://github.com/texane/stlink)
this tool works also on windows but there i would use the stlink plugin
the commandline is pretty straight forward 
~~~
copy: st-flash [--serial <serial>] write <image_path> 0x80000000
reset: st-flash [--serial <serial>] reset
~~~
thank you

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
