### ISSUE TITLE
[test] Greetea/HTrun out of sync with bootloader present

### ISSUE THREAD

**Issue by screamerbg** [ARMmbed/mbed-os-tools#74]
When the bootloader takes more time than expected, the sync message never reaches the test application.

Steps to reproduce:
1. Import `https://github.com/ARMmbed/smcc-tests`
2. Checkout branch `htrun-bl-desync`
3. Run tests with `mbed test -t ARM -m K64F -n simple-mbed-cloud-client-tests-dev_mgmt-connect* -v`

If you connect to the board using `mbed sterm -b 115200` you can pass it a fake sync message, e.g. `{{__sync;0}}` and the test will start normally.

@bridadan @theotherjimmy

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
This was closed by the automated bot by mistake - re-opening
