### ISSUE TITLE
[test] Version test spec

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbed-os-tools#75]
Currently test spec is missing version number. With time we would modify/enhance the test spec. In order maintain compatibility and may be some level of backward compatibility we need to version the test spec.

New test spec version will be instantiated by the build system as that is the source of the spec. Test spec version can not be build system version as spec does not need to change for every new build system version.

Greentea will have hard code to the version(s) that it supports. It can raise error for versions is does not support. Example: "Version p.q.r is no more supported" or "Update Greentea to support version x.y.z".

The less we change test spec version is better. This will keep build system and Greentea compatible most of the times.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
