### ISSUE TITLE
[test] mbedgt: can test case sort be removed ?

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-tools#77]
Hi

I would prefer that test case status is not sorted during mbedgt execution.

Ex:
Tested command: mbed test -t ARM -m NUCLEO_F070RB -vv -n tests-mbedmicro-rtos-mbed-threads

We can see the test suite execution :

[1473239592.78][CONN][RXD] >>> Running case #1: 'Testing single thread'...
[1473239592.98][CONN][RXD] >>> Running case #2: 'Testing parallel threads'...
[1473239593.18][CONN][RXD] >>> Running case #3: 'Testing serial threads'...

Then the test suite status:

mbedgt: test suite 'tests-mbedmicro-rtos-mbed-threads' ............................................... TIMEOUT in 50.15 sec
        test case: 'Testing parallel threads with wait' .............................................. OK in 0.17 sec
        test case: 'Testing single thread with wait' ................................................. OK in 0.15 sec
        test case: 'Testing serial threads with yield' ............................................... OK in 0.06 sec
        test case: 'Testing single thread with yield' ................................................ OK in 0.06 sec
        test case: 'Testing serial threads with wait' ................................................ OK in 1.06 sec
        test case: 'Testing single thread' ........................................................... OK in 0.06 sec
        test case: 'Testing parallel threads with child' ............................................. ERROR in 0.00 sec

==> Can this status can be displayed in the right order?

For report, I think we can keep the sort.

Thx

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
