### ISSUE TITLE
[test] detection of host test not consistent when using the -n option

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-os-tools#78]
when I use the -n "tests-unit-unittest"
the host test can be detected in "TESTS/unit/host_tests"

But if I don't use the -n option
the host test have to reside in "TESTS/host_tests" in order to be detected.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
