### ISSUE TITLE
[test] host test detection does not support custom build directories

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-os-tools#79]
if I compile program with mbed test --build <build-dir> option, the host test detection will fail.

This method used to detect host test direction is not robust https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_test_api.py#L160

In theory, the test_spec.json already give a "base_path" field to tell mbedgt what the base build directory is. This would be a more robust way to detecting relative path of host tests.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
