### ISSUE TITLE
[test] sending more than 45 characters from host test fails

### ISSUE THREAD

**Issue by thinkberg** [ARMmbed/mbed-os-tools#81]
On a NRF52_DK:

I am using a host test as a server side emulation. I need to pass base64 encoded strings back and forth. This works fine for DUT -> HOST, but HOST -> DUT fails if the value is longer than approx. 45 characters. You can use the host test `@event_callback` below to test this. If you remove the last 5-9 characters it works.

```python
    @event_callback("messageLength")
    def __messageLength(self, key, value, timestamp):
        self.send_kv("testLongMessage", "1234567890123456789012345678901234567890123456789")
````

The corresponding Test is:

```C++
void TestLongMessage() {
    char k[48], v[255];
    greentea_send_kv("messageLength", "start");
    greentea_parse_kv(k, v, sizeof(k), sizeof(v));
    greentea_send_kv(k,v);
}
```

Side note: debugging this appeard to read more than 45 characters but at some point only trash was read from the serial, so I cannot say whether it's the python side that might break things.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
