### ISSUE TITLE
[test] programming with flash tools that don't enumerate as a MSD

### ISSUE THREAD

**Issue by Alex-EEE** [ARMmbed/mbed-os-tools#82]
Hi @theotherjimmy and @bridadan , thanks again for all the great info yesterday!

It's looking like we can't buy those DIPdaps anymore, so can we revisit the idea of programming an mbed target via a flasher that *does not* enumerate as a mass storage device?  It would be used via the command line.  I know yesterday we were talking about how there would be an issue around target detection, any more thoughts on the direction we should head in trying to work around that?  Happy to back contribute whatever we come up with!

**Comment by geoffrey-vl** [comment]
Have any idea's been discussed or proposed internally on how and when we can tackle this issue?

**Comment by loverdeg-ep** [comment]
The professional  sector of the Mbed community very obviously needs this.

Related issues:
https://github.com/ARMmbed/mbed-os/issues/10009
https://github.com/ARMmbed/DAPLink/issues/577
https://github.com/ARMmbed/DAPLink/pull/559
https://github.com/ARMmbed/mbed-cli/issues/475

**Comment by loverdeg-ep** [comment]
@maclobdell

**Comment by Alex-EEE** [comment]
We have j link working as a program and reset plugin, but I think it gets past mbed ls bc we still have daplink for serial over usb.  I think what is needed is a command line switch to skip MSD detection altogether.

**Comment by geoffrey-vl** [comment]
Yes, that would help.
I've also setup a script that:
1. calls `mbed test --compile` to compile the greentea
2. calls `mbedhtrun` directly with the compiled binary

I can run my greentea tests this way, but off course the middle layer which is greentea itself is left out here and it would be truly great if we could have it parse the mbedhtrun output

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
