### ISSUE TITLE
[detect] identify board when daplink is in bootloader mode

### ISSUE THREAD

**Issue by jupe** [ARMmbed/mbed-os-tools#85]
in automation point of view we would like to update daplink softare and identify devices with mbed-ls just like before. Problem is now that mbed-ls give totally different target_id when device is in bootloader mode and therefore we cannot identify same board than when daplink is in normal mode.

Proposal changes:
- `mbed-ls` give information when device is in bootloader or in normal mode (in json result only is enough for me)
- `mbed-ls` give exactly same `target_id` in bootloader mode as well as normal mode.
  
  This probably needs more work and investigate how to do, because it might affect daplink implementation as well (@c1728p9 comments?)

Anyway, this is almost mandatory because otherwise we have to create hacky solution to avoid these "missing features".

@PrzemekWirkus @bridadan @c1728p9 @RomanSaveljev

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
