### ISSUE TITLE
[detect] Mock interface difficult to use and error prone

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/mbed-os-tools#88]
Currently, to add a mock, you have to do some odd things:
```bash
mbedls -m "C006:VLBUNO51"
```
```bash
mbedls --mock="C006:VLBUNO51"
```
both add a mock for the target id `C006` and the platform name `VLBUNO51`.

While that my seem reasonable, it can also be done by:
```bash
mbedls --mock="+C006:VLBUNO51"
```
Which is a bit complicated.

Removing mocks are where things get nasty:
```bash
mbedls -m "-C006"
```
is in theory part of the syntax, but `-C006` is parsed as a flag.
```bash
mbedls --mock="-C006"
```
is the only working way to actually remove a mock.
The readme also gives the impression that:
```bash
mbedls --mock="!C006"
```
should work, but it does not. Instead, it gives you a lovely trackback:
```
Traceback (most recent call last):
  File "/usr/bin/mbedls", line 11, in <module>
    load_entry_point('mbed-ls==1.3.2', 'console_scripts', 'mbedls')()
  File "/usr/lib/python3.6/site-packages/mbed_lstools/main.py", line 258, in mbedls_main
    ret_code = args.command(mbeds, args)
  File "/usr/lib/python3.6/site-packages/mbed_lstools/main.py", line 127, in mock_platform
    mbeds.mock_manufacture_id(mid, 'dummy', oper=oper)
  File "/usr/lib/python3.6/site-packages/mbed_lstools/lstools_base.py", line 231, in mock_manufacture_id
    raise ValueError("oper can only be [+-]")
ValueError: oper can only be [+-]
```

A much better interface would be:
```bash
mbedls add-mock C006 VLBUNO51
```
for add and:
```bash
mbedls rm-mock C006
```
or
```bash
mbedls remove-mock C006
```
for mock removal.

@yennster @bridadan Does this cover our offline discussion?

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
