### ISSUE TITLE
[detect] Push policy decisions outside of the core library

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/mbed-os-tools#89]
Currently, mbedls prints for users through logging inside of the object created by `mbed_lstools.create` This is a policy decision, and should be left up to consumers of the library or the command line interface.

In short:
 * Policy decisions, like what to do when a target does not have a mount point, should be decided by the API consumer.
 * Any printing, logging or other side effect outside of the defined API indicates a bug in mbedls, or in the consumer (similar to deprecation warnings).
 * Conditions that may indicate bugs should be logged.

This implies that:
 1. several warning invocations should become debug or info
 2. the `list_mbeds()` function must provide enough information to the API user to reconstruct the warnings that are currently logged
 3.  the `list_mbeds()` function should provide an "ergonomic" method for an API user to discover that one of the warning conditions has been encountered, making this discovery easy and/or explicit. This may be a documentation task, or include new API design.

1 and 2 should come as a single PR, possibly before 3.

@c1728p9 Did this capture our offline discussion?

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
