### ISSUE TITLE
[detect] Uninstall doesn't remove platforms.json

### ISSUE THREAD

**Issue by juhhov** [ARMmbed/mbed-os-tools#90]
If user wants to downgrade mbed-ls to earlier release platforms.json must be manually deleted since the newer version might not be backwards compatilble. This happens at least when downgrading from 1.4 to 1.3.7.

Pip uninstall should remove platforms.json.

**Comment by bridadan** [comment]
From what I've been reading, the methods that allow you to do post install/uninstall scripts aren't documented or are unsupported. With the update mentioned above in version v1.4.0 this shouldn't be an issue anymore.
