### ISSUE TITLE
[detect] Print a warning if multiple devices are mounted to the same mount point

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-os-tools#92]
This came up during #363. It may be helpful to users to print a warning if multiple devices share a mount point. Linux lets you do this but it will cause Mbed LS to give bogus results. Typically multiple Mbed devices sharing a mount point is a mistake anyway, so this would give users a helpful reminder.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
