### ISSUE TITLE
[detect] Remove 'unknown' string return types from the API

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-os-tools#93]
There are a few device results that are returned as `'unknown'` instead of the more Pythonic `None`. One of these data points is `device_type`. I think there may be more. `'unknown` should really only be used when printing results, if then at all.

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
